services:

  mysql:
    image: mysql:8.0
    container_name: moviehub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: moviehub
      MYSQL_USER: moviehub
      MYSQL_PASSWORD: moviehub123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    container_name: moviehub-backend
    restart: always
    env_file:
      - ./Backend/.env
    depends_on:
      - mysql
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: moviehub-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
